"""
This script cleans the JSON files generated by `scraper.py`.
"""

import json
from pathlib import Path


def remove_constant_items() -> None:
    builds_dir = Path("builds")
    for file in builds_dir.iterdir():
        if file.is_file():
            with file.open() as f:
                data = json.load(f)
            new_data = [
                row
                for row in data
                if (
                    "unique" not in row[0].lower()
                    and "best in slot" not in row[0].lower()
                )
            ]
            with file.open("w") as f:
                json.dump(new_data, f, indent=2)


def run() -> None:
    remove_constant_items()
