name: Daily Data Update

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Commit and push if changed
        uses: EndBug/add-and-commit@v9
        # overwrite all the json files in the repo if they have changed
        with:
          add: "**/*.json"
          message: "Daily update: ${{ steps.date.outputs.date }}"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
